config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :custom_fields, except: :show
  resource :dashboards, only: [:index, :show]

  devise_for :users
  
  root 'dashboards#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_many :contact_fields, dependent: :destroy

  validates :name, :email, presence: true

  default_scope { where(deleted_at: nil) }

  def destroy
    return super if deleted_at.present?
    update_attribute(:deleted_at, Time.now)
    DeletedCleanupJob.perform_later
  end
end

app/models/contact_field.rb
class ContactField < ActiveRecord::Base
  belongs_to :custom_field
  belongs_to :contact

  validates :custom_field_id, presence: true, uniqueness: { scope: :contact_id }

  default_scope { where(deleted_at: nil) }

  def destroy
    return super if deleted_at.present?
    update_attribute(:deleted_at, Time.now)
    DeletedCleanupJob.perform_later
  end
end

app/models/custom_field.rb
class CustomField < ActiveRecord::Base
  belongs_to :user
  has_many :contact_fields, dependent: :destroy

  validates :name, :field_type, :user_id, presence: true
  validates :name, uniqueness: { scope: :user_id }
  validates :field_type, inclusion: { in: %w(text text_area select) }

  default_scope { where(deleted_at: nil) }

  def destroy
    return super if deleted_at.present?
    update_attribute(:deleted_at, Time.now)
    DeletedCleanupJob.perform_later
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :custom_fields
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = current_user.contacts
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user
    assemble_customs

    if @contact.save
      redirect_to @contact, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  def update
    if @contact.update(contact_params)
      assemble_customs
      redirect_to @contact, notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_contact
    @contact = current_user.contacts.where(id: params[:id]).includes(:contact_fields).first
  end

  def contact_params
    params.require(:contact).permit(:name, :email)
  end

  def assemble_customs
    params[:customs].first.each_pair do |id, value|
      field = @contact.contact_fields.detect { |cf| cf.custom_field_id == id } || @contact.contact_fields.build(custom_field_id: id)
      next if value.blank? && field.new_record?
      field.value = value
      field.save if field.persisted?
    end
  end
end

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_custom_field, only: [:show, :edit, :update, :destroy]

  def index
    @custom_fields = current_user.custom_fields
  end

  def new
    @custom_field = CustomField.new
  end

  def edit
  end

  def create
    @custom_field = CustomField.new(custom_field_params)
    @custom_field.user = current_user

    if @custom_field.save
      redirect_to custom_fields_path, notice: 'Field was successfully created.'
    else
      render :new
    end
  end

  def update
    if @custom_field.update(custom_field_params)
      redirect_to custom_fields_path, notice: 'Field was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @custom_field.destroy
    respond_to do |format|
      format.html { redirect_to custom_fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_custom_field
    @custom_field = current_user.custom_fields.find(params[:id])
  end

  def custom_field_params
    params.require(:custom_field).permit(:name, :field_type, :value)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    return redirect_to contacts_path if user_signed_in?
    redirect_to '/users/sign_in'
  end

  def show
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def field(custom_field: , value: '', html_options: {})
    field_name = "customs[][#{custom_field.id}]"
    case custom_field.field_type.to_sym
    when :text
      text_field_tag(field_name, value, html_options)
    when :text_area
      text_area_tag(field_name, value, html_options)
    when :select
      select_tag field_name, options_for_select(custom_field.value.split(','), value), prompt: 'Select a value'
    end
  end
end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper
  def show_value?
    @custom_field.field_type == 'select'
  end
end

app/views/contacts/_form.html.erb
<%= render partial: 'shared/flash' %>

<%= form_for(@contact, html: { class: 'form-horizontal' }) do |f| %>
  <%= render partial: 'shared/errors', locals: { object: @contact } %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-xs-2' %>
    <div class="col-xs-10"><%= f.text_field :name, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: 'control-label col-xs-2' %>
    <div class="col-xs-10"><%= f.text_field :email, class: 'form-control' %></div>
  </div>

  <% current_user.custom_fields.each do |custom_field| %>
    <div class="form-group">
      <%= label_tag(custom_field.name.downcase, nil, class: 'control-label col-xs-2', for: "customs__#{custom_field.id}") %>
      <div class="col-xs-10"><%= field(custom_field: custom_field, value: @contact.contact_fields.detect { |cf| cf.custom_field_id == custom_field.id }.try(:value), html_options: { class: 'form-control' }) %></div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit('Create', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<%= render partial: 'shared/flash' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td>
          <%= link_to "<span class='glyphicon glyphicon-search'></span>".html_safe, contact %> |
          <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_contact_path(contact) %> |
          <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, contact, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<%= render partial: 'shared/flash' %>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<% current_user.custom_fields.each do |custom_field| %>
  <p>
    <strong><%= custom_field.name %>:</strong>
    <%= @contact.contact_fields.detect { |cf| cf.custom_field_id == custom_field.id }.try(:value) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/custom_fields/_form.html.erb
<%= render partial: 'shared/flash' %>

<%= form_for(@custom_field, html: { class: 'form-horizontal' }) do |f| %>
  <%= render partial: 'shared/errors', locals: { object: @custom_field } %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-xs-2' %>
    <div class="col-xs-10"><%= f.text_field :name, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :field_type, class: 'control-label col-xs-2' %>
    <div class="col-xs-10">
      <%= f.select(:field_type, [['Text', 'text'], ['Text Area', 'text_area'], ['Select', 'select']], { prompt: '' }, { 'data-control' => 'type' }) %>
    </div>
  </div>

  <div class="form-group hide" data-group='select'>
    <%= f.label :value, class: 'control-label col-xs-2' %>
    <div class="col-xs-10"><%= f.text_field :value, class: 'form-control', placeholder: 'Fill the select options using , as separator' %></div>
  </div>

  <div class="actions">
    <%= f.submit('Create', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/custom_fields/edit.html.erb
<h1>Editing Custom Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @custom_field %> |
<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/index.html.erb
<%= render partial: 'shared/flash' %>

<h1>Custom Fields</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_fields.each do |custom_field| %>
      <tr>
        <td><%= custom_field.name %></td>
        <td>
          <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_custom_field_path(custom_field) %>
          |
          <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, custom_field, method: :delete, data: { confirm: 'Are you sure? All contact fields will be deleted too!' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom field', new_custom_field_path %>

app/views/custom_fields/new.html.erb
<h1>New Custom Field</h1>

<%= render 'form' %>

<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/show.html.erb
<%= render partial: 'shared/flash' %>

<p>
  <strong>Name:</strong>
  <%= @custom_field.name %>
</p>

<p>
  <strong>Field type:</strong>
  <%= @custom_field.field_type %>
</p>

<p>
  <strong>Delete at:</strong>
  <%= @custom_field.delete_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @custom_field.user %>
</p>

<p>
  <strong>Contact field:</strong>
  <%= @custom_field.contact_field %>
</p>

<%= link_to 'Edit', edit_custom_field_path(@custom_field) %> |
<%= link_to 'Back', custom_fields_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClientsManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'shared/navbar' if user_signed_in? %>

<div id='container'>
  <%= yield %>
</div>


</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this custom_field from being saved:</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% { notice: 'alert-success', info: 'alert-info', warning: 'alert-warning' }.each_pair do |key, klass| %>
    <%= content_tag(:div, flash[key], class: "alert #{klass}") if flash[key] %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to('Contacts', contacts_path, class: 'navbar-brand')%>
      <%= link_to('Custom Fields', custom_fields_path, class: 'navbar-brand')%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to('Settings', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>